[package]
name = "cadency_commands"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.14"
reqwest = "0.11.6"

[dependencies.serde]
version = "1.0.130"
features = ["derive"]

[dependencies.serenity]
version = "0.11.5"
default-features = false
features = ["client", "gateway", "rustls_backend", "model", "voice", "cache"]

[dependencies.songbird]
version = "0.3.0"
features = ["builtin-queue", "yt-dlp"]

[dependencies.cadency_core]
path = "../cadency_core"

[dependencies.cadency_codegen]
path = "../cadency_codegen"

[dependencies.cadency_yt_playlist]
path = "../cadency_yt_playlist"

[dev-dependencies.tokio]
version = "1.13.0"
features = ["macros", "rt-multi-thread"]



